CREATE TABLE POLITICA (
	ID SERIAL PRIMARY KEY,
	P_VITORIA VARCHAR(10),
	P_EMPATE VARCHAR(10),
	P_DERROTA VARCHAR(10),
	PERMISSAO BOOLEAN
);
CREATE TABLE COMPETIDOR (
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL
);
CREATE TABLE COMPETICAO(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(45) NOT NULL,
	DT_INICIO DATE,
	DT_FIM DATE,
	POLITICA_ID INT,
	FOREIGN KEY (POLITICA_COD)  REFERENCES  POLITICA(ID)
);
CREATE TABLE PARTICIPACAO(
	COLOCACAO INT,
	PREMIO DOUBLE PRECISION,
	COMPETIDOR_ID INT,
	COMPETICAO_ID INT,
	FOREIGN KEY(COMPETIDOR_ID) REFERENCES COMPETIDOR(ID),
	FOREIGN KEY(COMPETICAO_ID) REFERENCES COMPETICAO(ID)
);
CREATE TABLE EVENTO(
  	ID SERIAL PRIMARY KEY,
	VENCEDOR_COD INT,
	COMPETIDOR1_ID INT,
	COMPETIDOR2_ID INT,
	COMPETICAO_ID INT,
	FOREIGN KEY(COMPETIDOR1_ID) REFERENCES COMPETIDOR(ID),
	FOREIGN KEY(COMPETIDOR2_ID) REFERENCES COMPETIDOR(ID),
	FOREIGN KEY(COMPETICAO_ID) REFERENCES COMPETICAO(ID)
);